name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: docker compose -f test.compose.yml run app_test
